// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbEm1nBs3JmTZAd1fJOlM1IyJmueAngFg',
    appId: '1:363644811858:web:7e033037b410e9d43cbd8b',
    messagingSenderId: '363644811858',
    projectId: 'bootstrap-project-c740a',
    authDomain: 'bootstrap-project-c740a.firebaseapp.com',
    storageBucket: 'bootstrap-project-c740a.firebasestorage.app',
    measurementId: 'G-XX9CPV39M7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA_fDDvMP1VDKIfu7vg1-EP1b4Kr1ZXns',
    appId: '1:363644811858:android:42e13e45d5d238a33cbd8b',
    messagingSenderId: '363644811858',
    projectId: 'bootstrap-project-c740a',
    storageBucket: 'bootstrap-project-c740a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt9VMjnYKJErOIjgYS-2QTC4fTjw5BFDg',
    appId: '1:363644811858:ios:0d12cda33b1eb8113cbd8b',
    messagingSenderId: '363644811858',
    projectId: 'bootstrap-project-c740a',
    storageBucket: 'bootstrap-project-c740a.firebasestorage.app',
    iosBundleId: 'com.example.bootstrapProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt9VMjnYKJErOIjgYS-2QTC4fTjw5BFDg',
    appId: '1:363644811858:ios:0d12cda33b1eb8113cbd8b',
    messagingSenderId: '363644811858',
    projectId: 'bootstrap-project-c740a',
    storageBucket: 'bootstrap-project-c740a.firebasestorage.app',
    iosBundleId: 'com.example.bootstrapProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbEm1nBs3JmTZAd1fJOlM1IyJmueAngFg',
    appId: '1:363644811858:web:bcbe2e25a9ea42ba3cbd8b',
    messagingSenderId: '363644811858',
    projectId: 'bootstrap-project-c740a',
    authDomain: 'bootstrap-project-c740a.firebaseapp.com',
    storageBucket: 'bootstrap-project-c740a.firebasestorage.app',
    measurementId: 'G-N5TBD71Y1C',
  );

}